### ISSUE TITLE
Критична помилка ініціалізації баз даних Questie через аддон QuestieUkrainianTranslation! (Високий приорітет)

### ISSUE THREAD

**Issue by Wilford1990** [Jakanis/QuestieUkrainianTranslation#1]
Доброго дня! Слава Україні!

Після останнього оновлення аддону Questie до версії v.10.0.0 аддон QuestieUkrainianTranslation почав спричиняти помилку ініціалізацій баз даних аддону Questie (скриншот додається).

Факт спричинення помилки саме аддоном QuestieUkrainianTranslation був визначений методом виключення і перебору. Були вимкнені усі аддони і саме аддон QuestieUkrainianTranslation став причиною виникнення даної помилки. При вимкненні аддону QuestieUkrainianTranslation аддон Questie працює і його бази оновлюються без нарікань.

Прохання випустити хотфікс, за можливості, ближчим часом.

Величезне дякую за Вашу колосальну роботу.

![WoWScrnShot_042924_182155](https://github.com/Jakanis/QuestieUkrainianTranslation/assets/155723803/0d1001b5-8b46-47f6-8a55-17221c2da921)

**Comment by Jakanis** [comment]
Щиро дякую, помилку виправив (в Questie v10.0.0 додали підтримку Cataclysm, а перекладу для археології не було)
Оновлення вже доступне на CurseForge

**Comment by Wilford1990** [comment]
> Щиро дякую, помилку виправив (в Questie v10.0.0 додали підтримку Cataclysm, а перекладу для археології не було) Оновлення вже доступне на CurseForge

Величезне дякую!
